title: Fudan Dynamics (SCMS + SMS)
url: "https://dlidynamics.github.io"
baseurl: "/fudandynamics"   # 注意前面有 /，后面不要 /
timezone: Asia/Shanghai
markdown: kramdown
collections:
  seminars:
    output: false   # 原来是 true；现在不生成 /seminars/:name/ 的详情页
  events:
    output: false
